version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/priovar.
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
  
  spring-boot-backend:
    build:
      context: ./backend/priovar
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=priovar.
      - FLASK_URL=http://flask-backend:5000
  
  flask-backend:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    environment:
      - FLASK_APP=app.py
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=priovar.
  
  react-frontend:
    build:
      context: ./frontend_cs491_org  # Replace with the path to your React app
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container
    depends_on:
      - flask-backend  # If the frontend depends on the backend service

networks:
  default:
    driver: bridge
