version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/priovar.
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
  
  flask-backend:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    environment:
      - FLASK_APP=flask/app.py

networks:
  default:
    driver: bridge
